//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otobus_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifeTablosu
    {
        public int tarifeID { get; set; }
        public string kalkisNoktasi { get; set; }
        public string varisNoktasi { get; set; }
        public Nullable<decimal> biletFiyati { get; set; }
        public string plakaNo { get; set; }
        public string marka { get; set; }
    }
}
